const PAWAPAY_DEPOSIT_URL = 'https://api.sandbox.pawapay.io/v2/deposits';

const PAWAPAY_TRANSACTION_STATUS = {
    PROCESSING: 'PROCESSING'.toUpperCase(),
    COMPLETED: 'COMPLETED'.toUpperCase(),
    FAILED: 'FAILED'.toUpperCase(),
    CANCELLED: 'CANCELLED'.toUpperCase(),
}

const PAWAPAY_TRANSACTION_CURRENCY = 'XAF'.toUpperCase();
const PAWAPAY_TRANSACTION_COUNTRY = 'CMR'.toUpperCase();
const PAWAPAY_TRANSACTION_TYPE = 'Deposit';
const PAWAPAY_TRANSACTION_CANAL = 'MMO'.toUpperCase();

module.exports = {
    PAWAPAY_DEPOSIT_URL,
    PAWAPAY_TRANSACTION_STATUS,
    PAWAPAY_TRANSACTION_CURRENCY,
    PAWAPAY_TRANSACTION_COUNTRY,
    PAWAPAY_TRANSACTION_TYPE,
    PAWAPAY_TRANSACTION_CANAL,
}